@AppHost_HostAddress = http://localhost:5151

GET {{AppHost_HostAddress}}/api/building?query=pa
Accept: application/json

###
GET {{AppHost_HostAddress}}/api/building/355
Accept: application/json

###
GET {{AppHost_HostAddress}}/api/building/chapters
Accept: application/json

###
GET {{AppHost_HostAddress}}/api/building/observation/166
Accept: application/json

###
GET {{AppHost_HostAddress}}/api/building/355/excel
Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet